[package]
name = "simple-poc"
version = "0.1.0"
authors = ["Martin Kayondo <kayondo@snu.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
